### ISSUE TITLE
Error on starting application in fork mode with HTTP server

### ISSUE THREAD

**Issue by onpagecorp** [jon-hall/pm2-windows-service#26]
Very simple NodeJS HTTP server started in fork mode ended with exception:

> 1|server   | Error: listen EADDRINUSE 0.0.0.0:5674
> 1|server   |     at Object.exports._errnoException (util.js:1022:11)
> 1|server   |     at exports._exceptionWithHostPort (util.js:1045:20)
> 1|server   |     at Server._listen2 (net.js:1262:14)
> 1|server   |     at Server._listen2 C:\USERS\USER\APPDATA\ROAMING\NPM\node_modules\pm2\node_modules\async-listener\index.js:51:23)
> 1|server   |     at listen (net.js:1298:10)
> 1|server   |     at doListening (net.js:1397:7)
> 1|server   |     at _combinedTickCallback (internal/process/next_tick.js:77:11)
> 1|server   |     at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)
> 1|server   |     at Module.runMain (module.js:607:11)
> 1|server   |     at run (bootstrap_node.js:420:7)
> 1|server   |     at startup (bootstrap_node.js:139:9)
> 1|server   |     at bootstrap_node.js:535:3

**Comment by jon-hall** [comment]
Hi, sorry you're getting issues with this, if you could answer a few questions to clarify exactly what your setup is:

1. What versions of `windows`, `node`, and `pm2` are you using?
2. Have you configured your environment as part of the `pm2-windows-service` setup?  If so, are you able to post up (sanitised) values for the various `pm2-windows-service` environment variables?
3. Have you checked the [caveats](https://github.com/jon-hall/pm2-windows-service#caveats) section to confirm that nothing mentioned there may be causing you issues?
4. Does running the same application directly with `node` work?  Does running it directly with `pm2` over the commandline work (e.g. with `pm2 start`)?

That should be enough information to get me started on figuring out why you're getting an error running (what should be) a simple app to launch, thanks.

**Comment by jon-hall** [comment]
Closing this since there's been no activity in a while, feel free to reopen or raise a new issue if needed.
