### ISSUE TITLE
"Sorry, this script requires pm2" - environment variable issue?

### ISSUE THREAD

**Issue by chrisevans1001** [jon-hall/pm2-windows-service#43]
Hi. I'm having some trouble getting PM2 working as a service using this code. To explain what I have done so far:

NPM global install directory set to: C:\ProgramData\npm\
NPM global cache set to: C:\ProgramData\npm-cache\

pm2 and pm2-windows-service installed globally.

I have set up pm2 and it works fine, I can run 'pm2 resurrect' from any user account and the apps are launched successfully. I have run pm2-install-service and followed the instructions. Environment variables are set up as follows within the system variables:

PM2_HOME : C:\etc\pm2_home\
PM2_SERVICE_PM2_DIR : C:\ProgramData\npm\
PM2_SERVICE_SCRIPTS : y
Path : (includes others);C:\ProgramData\npm\

When I try to start the service, it shows started in services then almost immediately stops. The log file shows:

```
Sorry, this script requires pm2
C:\ProgramData\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js:177
    child.send('shutdown');
         ^

TypeError: Cannot read property 'send' of null
    at process.killkid (C:\ProgramData\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js:177:10)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process.exit (internal/process.js:156:15)
    at monitor (C:\ProgramData\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js:99:17)
    at ChildProcess.<anonymous> (C:\ProgramData\npm\node_modules\pm2-windows-service\node_modules\node-windows\lib\wrapper.js:170:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

From my own digging, this appears to indicate an environment variable issue but I am at a loss as to what exactly given I can run node, npm and pm2 from any user account within cmd.

Any suggestions?

Thanks

**Comment by chrisevans1001** [comment]
Having read through the code, I see that the PM2_SERVICE_PM2_DIR directory needs to be the PM2 directory within node_modules, not the root (at least that is my interpretation). I have therefore altered it to C:\ProgramData\npm\node_modules\pm2\ which means I no longer get the "Sorry, this script requires PM2" error. However, I now get the following:

```
C:\ProgramData\npm\node_modules\pm2-windows-service\src\service.js:88
            throw err;
            ^

Error: script not found : C:\Windows\system32\y
    at Object.Common.resolveAppAttributes (C:\ProgramData\npm\node_modules\pm2\lib\Common.js:563:11)
    at C:\ProgramData\npm\node_modules\pm2\lib\API.js:793:33
    at C:\ProgramData\npm\node_modules\pm2\node_modules\pm2-axon-rpc\lib\client.js:45:10
    at Parser.<anonymous> (C:\ProgramData\npm\node_modules\pm2\node_modules\pm2-axon\lib\sockets\req.js:67:8)
    at emitOne (events.js:115:13)
    at Parser.emit (events.js:210:7)
    at Parser._write (C:\ProgramData\npm\node_modules\pm2\node_modules\amp\lib\stream.js:91:16)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Parser.Writable.write (_stream_writable.js:274:11)
```

**Comment by chrisevans1001** [comment]
Finally, I discovered that the PM2_SERVICE_SCRIPTS needed deleting as I wasn't intent on using them, only pm2 resurrect. I'll have a look and see if I can make anything clearer for others in future. :)

**Comment by tony-0tis** [comment]
If you using yarn instead of npm you have to set PM2_SERVICE_PM2_DIR to C:\Users\USER\AppData\Local\Yarn\Data\global\node_modules\pm2\index.js
