### ISSUE TITLE
Error: Illegal characters in path.

### ISSUE THREAD

**Issue by paul4156** [jon-hall/pm2-windows-service#68]
After installing pm2-windows-service, PATH was set incorrectly. The removal of package does not revert PATH.

So I got the following error when running pm2.

```
 pm2 start ecosystem.config.js
Error: Illegal characters in path.
    at pathArg (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\lib\path-arg.js:20:27)
    at Function.mkdirpSync [as sync] (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:18:10)
    at module.exports.Client.initFileStructure (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:133:25)
    at new module.exports (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:38:8)
    at new API (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\API.js:108:19)
    at Object.<anonymous> (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\binaries\CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Error: Illegal characters in path.
    at pathArg (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\lib\path-arg.js:20:27)
    at Function.mkdirpSync [as sync] (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\node_modules\mkdirp\index.js:18:10)
    at module.exports.Client.initFileStructure (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:141:25)
    at new module.exports (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\Client.js:38:8)
    at new API (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\API.js:108:19)
    at Object.<anonymous> (C:\Users\paul4156\AppData\Roaming\npm\node_modules\pm2\lib\binaries\CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

Can we restore previous PATH when pm2-windows-service is removed? Thanks.

**Comment by esopht** [comment]
Yes, you can restore previous path when pm2-windows-service is removed. What you have to do is remove the **PM2** related configuration in Environment Variables

**Comment by jon-hall** [comment]
Closing this as the package is now deprecated, users should migrate to [`pm2-installer`](https://github.com/jessety/pm2-installer).
