### ISSUE TITLE
Service crash at start up

### ISSUE THREAD

**Issue by s-a** [jon-hall/pm2-windows-service#8]
Error log: \AppData\Roaming\npm\node_modules\pm2-windows-service\src\daemon\pm2.err.log

```
C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:49
    if (obj.hasOwnProperty(attr)) {
            ^

TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:49:13)
    at safeDeepClone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:53:22)
    at cloneWrap (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:65:10)
    at Object.clone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\Utility.js:39:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\Common.js:151:18)
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God.js:379:23
    at forkMode (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God.js:231:15)
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God\ForkMode.js:203:22
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\async\lib\async.js:52:16
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\async\lib\async.js:1209:30
C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:49
    if (obj.hasOwnProperty(attr)) {
            ^

TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:49:13)
    at safeDeepClone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:53:22)
    at cloneWrap (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:65:10)
    at Object.clone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\Utility.js:39:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\Common.js:151:18)
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God.js:379:23
    at forkMode (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God.js:231:15)
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God\ForkMode.js:203:22
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\async\lib\async.js:52:16
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\async\lib\async.js:1209:30
C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:49
    if (obj.hasOwnProperty(attr)) {
            ^

TypeError: obj.hasOwnProperty is not a function
    at safeDeepClone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:49:13)
    at safeDeepClone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:53:22)
    at cloneWrap (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\safe-clone-deep\src\index.js:65:10)
    at Object.clone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\Utility.js:39:12)
    at Object.Common.deepCopy.Common.serialize.Common.clone (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\Common.js:151:18)
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God.js:379:23
    at forkMode (C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God.js:231:15)
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\pm2\lib\God\ForkMode.js:203:22
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\async\lib\async.js:52:16
    at C:\Users\sahlf\AppData\Roaming\npm\node_modules\pm2-windows-service\node_modules\async\lib\async.js:1209:30
```

**Comment by s-a** [comment]
I figured out that this error happens on system reboot. When I run the service manually everything works as expected.

**Comment by jon-hall** [comment]
It looks like this might be due to the fact that the published version of this library runs an older version of PM2 (0.15.x) - since a very similar issue was reported on PM2's repo (https://github.com/Unitech/pm2/issues/2132) and was fixed by re-installing/updating PM2.

You can see if using a newer version of PM2 does address the issue by installing the latest version of this package from github and setting the `PM2_SERVICE_PM2_DIR` environment variable (more info on doing this is [in this issue](https://github.com/jon-hall/pm2-windows-service/issues/4#issuecomment-230151748)).  I'm hoping to finish off a small improvement I'm currently working on and get a new version published this weekend though if you'd prefer to hang on til then and update to 0.2.0 when it's out.

Additionally, something else which might be relevant to this issue - have you run `pm2 dump`/`pm2 save`, or are you using the `PM2_SERVICE_SCRIPTS` environment variable to control what PM2 tries to launch at startup?

**Comment by s-a** [comment]
Hmmm as far I can see this error occurs in the pm2 module right?

I am using pm2 v1.1.3 which might be the latest version currently and I tried both `pm2 save` to save a dump and `PM2_SERVICE_SCRIPTS`.

There was a situtation where is tried to start the service manually and everything worked as expected. This worked exatcly one time :) and then never again.

**Comment by s-a** [comment]
OK i got it :+1: 

I did 2 things to make it work.
- I changed the referenced pm2 version in this repo in package.json to the version I am currently using and typed `npm install`
  - https://github.com/jon-hall/pm2-windows-service/blob/d457ed2af1869f5360c2c16be1b54e7ea5f9b37d/package.json#L35
- I changed the pm2 windows 2 service setting "allow service to interact with desktop".

After that everthing is working.

Why do you use local pm2 version instead of global installed version? It might solve problems to use the global one.

**Comment by s-a** [comment]
Please check this out https://github.com/jon-hall/pm2-windows-service/pull/9
